language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install pip -U
  - pip install -q Django==$DJANGO
  - pip install pep8 -U
  - pip install pyflakes -U
  - pip install coveralls -U
  - pip install -q -e .
before_script:
  - "pep8 --exclude=migrations paiji2_weather"
  - pyflakes paiji2_weather
script:
  - coverage run --source=paiji2_weather manage.py test
  - python setup.py test
after_success:
  - coveralls
